name = "sher-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 */6 * * *"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "sher-uploads"

[[kv_namespaces]]
binding = "KV"
id = "6c08fefdc4394d559a0044111a7cecc1"
